#ifndef DEBUG_WND_SOME_CTRL_H

typedef enum
{
    DEBUG_WND_SOME_CTRL_PARAM1_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM1,
    DEBUG_WND_SOME_CTRL_PARAM2_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM2,
    DEBUG_WND_SOME_CTRL_PARAM3_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM3,

    DEBUG_WND_SOME_CTRL_PARAM4_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM4,

    DEBUG_WND_SOME_CTRL_PARAM5_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM5,
    DEBUG_WND_SOME_CTRL_PARAM6_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM6,
    DEBUG_WND_SOME_CTRL_PARAM7_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM7,
    DEBUG_WND_SOME_CTRL_PARAM8_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM8,
    DEBUG_WND_SOME_CTRL_PARAM9_STATIC,
    DEBUG_WND_SOME_CTRL_PARAM9,

    DEBUG_WND_SOME_CTRL_COMBOBOX1_STATIC,
    DEBUG_WND_SOME_CTRL_COMBOBOX1,
    DEBUG_WND_SOME_CTRL_PROGRESS_BAR,
    DEBUG_WND_SOME_CTRL_EXEC_BUTTON,

    DEBUG_WND_SOME_CTRL_MAX
}DEBUG_WND_SOME_CTRL_ID;

#define DEBUG_WND_SOME_CTRL_ID_OFFSET 10
#define MY_EX_STYLE (WS_EX_OVERLAPPEDWINDOW)

BOOL DebugWndSomeCtrlCreate(HINSTANCE hInst,HWND hwnd);
HWND DebugWndSomeCtrlGetHWND(DEBUG_WND_SOME_CTRL_ID id);
void DebugWndSomeCtrlEnable(DEBUG_WND_SOME_CTRL_ID id);
void DebugWndSomeCtrlDisable(DEBUG_WND_SOME_CTRL_ID id);
BOOL DebugWndSomeCtrlGetText( DEBUG_WND_SOME_CTRL_ID id, PTSTR ptstrText );

#define DEBUG_WND_SOME_CTRL_H
#endif /* DEBUG_WND_SOME_CTRL_H */
